"""empty message

Revision ID: 1dd96c4fd790
Revises: ab03dc04b0a4
Create Date: 2026-09-24 20:19:36.495712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd96c4fd790'
down_revision = 'ab03dc04b0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cursos_professor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('cursos_professor_id_fkey'), 'professores', ['professor_id'], ['id'])

    # ### end Alembic commands ###
