"""adiciona tabela de turmas

Revision ID: 377ef4e9bc99
Revises: 1dd96c4fd790
Create Date: 2026-09-24 20:36:58.661610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377ef4e9bc99'
down_revision = '1dd96c4fd790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('curso_id', sa.String(length=36), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    # ### end Alembic commands ###
