"""Cria demais tabelas

Revision ID: 4166b7297cac
Revises: 842ed6760f72
Create Date: 2026-09-23 00:59:34.211709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4166b7297cac'
down_revision = '842ed6760f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('numero_responsavel', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('numero_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('privilegio', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cursos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('nivel', sa.String(length=255), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('curso_id', sa.String(length=36), nullable=False),
    sa.Column('data_matricula', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'curso_id', name='uq_matricula_alunos_curso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matriculas')
    op.drop_table('cursos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
