"""adiciona tabela de turmas aluno

Revision ID: 4949f19d8d9b
Revises: 377ef4e9bc99
Create Date: 2026-09-24 20:52:29.877601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4949f19d8d9b'
down_revision = '377ef4e9bc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_alunos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('turma_id', sa.String(length=36), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'turma_id', name='uq_turma_aluno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_alunos')
    # ### end Alembic commands ###
