"""Cria tabelas iniciais

Revision ID: 842ed6760f72
Revises: 
Create Date: 2026-09-15 04:21:07.038235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842ed6760f72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade_uf', sa.String(length=100), nullable=True),
    sa.Column('graduacao_curso', sa.String(length=255), nullable=True),
    sa.Column('instituicao_ensino', sa.String(length=255), nullable=True),
    sa.Column('ano_conclusao', sa.Integer(), nullable=True),
    sa.Column('pos_graduacao', sa.String(length=255), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('privilegio', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professores')
    # ### end Alembic commands ###
