"""adiciona autenticacao para o professor

Revision ID: ab03dc04b0a4
Revises: 4166b7297cac
Create Date: 2026-09-24 16:43:28.931590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab03dc04b0a4'
down_revision = '4166b7297cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tentativas_falhas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_column('bloqueado_ate')
        batch_op.drop_column('tentativas_falhas')
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
