"""adiciona aula, avaliacao, anotacao e dados profissionais do professor

Revision ID: bed6d9ad5d9a
Revises: 4949f19d8d9b
Create Date: 2026-09-25 14:17:10.541025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed6d9ad5d9a'
down_revision = '4949f19d8d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anotacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('professor_id', sa.String(length=36), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aulas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('assunto', sa.String(length=255), nullable=True),
    sa.Column('materia', sa.String(length=255), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('turma_id', sa.String(length=36), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('aluno_id', sa.String(length=36), nullable=False),
    sa.Column('aula_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'aula_id', name='uq_avaliacao_aluno_aula')
    )
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_atuacao', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_contratacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_inicio_atividades', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professores', schema=None) as batch_op:
        batch_op.drop_column('data_inicio_atividades')
        batch_op.drop_column('tipo_contratacao')
        batch_op.drop_column('area_atuacao')

    op.drop_table('avaliacoes')
    op.drop_table('aulas')
    op.drop_table('anotacoes')
    # ### end Alembic commands ###
